--liquibase formatted sql
--changeset pacion:1
CREATE TABLE role
(
    role_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name    VARCHAR(255),
    CONSTRAINT pk_role PRIMARY KEY (role_id)
);

ALTER TABLE role
    ADD CONSTRAINT uc_role_name UNIQUE (name);

CREATE TABLE app_user
(
    user_id     BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    username    VARCHAR(255),
    email       VARCHAR(255),
    password    VARCHAR(255),
    first_name  VARCHAR(255),
    second_name VARCHAR(255),
    created     TIMESTAMP WITHOUT TIME ZONE,
    updated     TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_appuser PRIMARY KEY (user_id)
);

CREATE TABLE user_roles
(
    role_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL
);

ALTER TABLE app_user
    ADD CONSTRAINT uc_appuser_email UNIQUE (email);

ALTER TABLE app_user
    ADD CONSTRAINT uc_appuser_username UNIQUE (username);

ALTER TABLE user_roles
    ADD CONSTRAINT fk_userol_on_app_user FOREIGN KEY (user_id) REFERENCES app_user (user_id);

ALTER TABLE user_roles
    ADD CONSTRAINT fk_userol_on_role FOREIGN KEY (role_id) REFERENCES role (role_id);

CREATE TABLE category
(
    category_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name        VARCHAR(255),
    created     TIMESTAMP WITHOUT TIME ZONE,
    updated     TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_category PRIMARY KEY (category_id)
);

CREATE TABLE transaction
(
    transaction_id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    transaction_type VARCHAR(255),
    value            INTEGER                                 NOT NULL,
    quantity         INTEGER                                 NOT NULL,
    title            VARCHAR(255),
    description      VARCHAR(255),
    category_id      BIGINT,
    appuser_id       BIGINT,
    created          TIMESTAMP WITHOUT TIME ZONE,
    updated          TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_transaction PRIMARY KEY (transaction_id)
);

ALTER TABLE transaction
    ADD CONSTRAINT FK_TRANSACTION_ON_APPUSER FOREIGN KEY (appuser_id) REFERENCES app_user (user_id);

ALTER TABLE transaction
    ADD CONSTRAINT FK_TRANSACTION_ON_CATEGORY FOREIGN KEY (category_id) REFERENCES category (category_id);