--liquibase formatted sql
--changeset pacion:2
CREATE TABLE app_user
(
    user_id     BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    username    VARCHAR(255),
    email       VARCHAR(255),
    password    VARCHAR(255),
    first_name  VARCHAR(255),
    second_name VARCHAR(255),
    created     TIMESTAMP WITHOUT TIME ZONE,
    updated     TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_appuser PRIMARY KEY (user_id)
);

CREATE TABLE user_roles
(
    role_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL
);

ALTER TABLE app_user
    ADD CONSTRAINT uc_appuser_email UNIQUE (email);

ALTER TABLE app_user
    ADD CONSTRAINT uc_appuser_username UNIQUE (username);

ALTER TABLE user_roles
    ADD CONSTRAINT fk_userol_on_app_user FOREIGN KEY (user_id) REFERENCES app_user (user_id);

ALTER TABLE user_roles
    ADD CONSTRAINT fk_userol_on_role FOREIGN KEY (role_id) REFERENCES role (role_id);